sudo: false
env:
  matrix:
  - MRUBY_REPO=https://github.com/mruby/mruby.git MRUBY_BRANCH=master
  - MRUBY_REPO=https://bitbucket.org/monami_ya_mrb/monami-ya.mrb.git MRUBY_BRANCH=master
  - MRUBY_REPO=https://bitbucket.org/monami_ya_mrb/monami-ya.mrb.git MRUBY_BRANCH=develop
script:
- ruby run_test.rb all test
branches:
  only:
  - master
notifications:
  hipchat:
    rooms:
      secure: Dnjn9BjsTk9lXfo4LiaiE2vTRc1zvx1VsMohAoH6lbv73+VFw7xjERIlGVMHi3OCXK3m4MPTtOeSNDKulNfqkFu/+yyxYH2RN/fC++lLyjfiRIa3yE/Wr37fS28a6XnlpnoQroIxgylxjuVzyripP1pmgfqEvcEtiHWd0lLmW4o=
